### ISSUE TITLE
Ban chat

### ISSUE THREAD

**Issue by ghost** [star-inc/lups#1]
After login ban chat

**Comment by supersonictw** [comment]
Because of the Policy of Line Corp., the "/api/v4/TalkService.do" "/api/v4j/TalkService.do" "/api/v3/TalkService.do" no longer to use :(
Our SuperLineAPI Full Version was fix the problem in 2018/07/08.
We will give the patch to the OpenSource Version ;)
Thanks for your report.

**Comment by ghost** [comment]
do you know how to login primary token?
Pada tanggal 19 Jul 2018 15:13, "SuperSonic" <notifications@github.com>
menulis:

**Comment by supersonictw** [comment]
The Token of Smartphone Device like "AuthKey"？
Well, it's very dangerous. You may lost your account forever.
I can't tell you how work it.

**Comment by ghost** [comment]
can you give your id line?




2018-07-25 21:26 GMT+08:00 SuperSonic <notifications@github.com>:

**Comment by muhmursalind** [comment]
how to use authkey for primary login?

can you give source code?


2018-07-25 21:46 GMT+08:00 Muh Mursalin Darmawan <muhmursalind@gmail.com>:

**Comment by supersonictw** [comment]
No, Sorry :(
